# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import items.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование альбома')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Характеристики альбома')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', items.fields.ThumbnailImageField(upload_to='photos')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Album')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['title'],
            },
        ),
    ]
